version: "3.9"
services:
  telegram_bot:
    container_name: telegram_bot
    restart: always
    ports:
      - "3003:3003"
    environment:
      TOKEN: ${TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - bot

networks:
  bot:
    driver: bridge